// <auto-generated />
using System;
using Giacom.CallDetails.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Giacom.CallDetails.Persistence.Migrations.Migrations
{
    [DbContext(typeof(CallDetailsDbContext))]
    [Migration("20231120120113_AddCallerDateTypeIndex")]
    partial class AddCallerDateTypeIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Giacom.CallDetails.Domain.CallDetails.CallDetail", b =>
                {
                    b.Property<string>("CallDetailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("date");

                    b.Property<int>("CallType")
                        .HasColumnType("int");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(4)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CallDetailId");

                    b.HasIndex("CallerId", "CallDate", "CallType");

                    b.ToTable("CallDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
